if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "INPUT_FILE and OUTPUT_FILE are required")
endif()

if(NOT EXISTS "${OUTPUT_FILE}")
    file(COPY_FILE "${INPUT_FILE}" "${OUTPUT_FILE}")
endif()
